### ISSUE TITLE
Test js files

### ISSUE THREAD

**Issue by lucia2007** [lucia2007/love-letter-generator#39]

**Comment by Cleg83** [comment]
**About js**

Errors:

![js-test-about](https://github.com/lucia2007/love-letter-generator/assets/144853399/e01c38b0-0c5b-4315-9170-ff5a030df23d)


Warnings: 

![js-test-about2](https://github.com/lucia2007/love-letter-generator/assets/144853399/92af8cbe-06e8-4a47-a531-17b6b3b04b54)
![js-test-about3](https://github.com/lucia2007/love-letter-generator/assets/144853399/f4cdd3d7-9b76-4151-baf4-b2ab3a31193a)

**Comment by Cleg83** [comment]
Mail js: 

![image](https://github.com/lucia2007/love-letter-generator/assets/144853399/1e751e57-080f-41b3-950a-9cd00f4b9d21)
